[INFO      ] 2023-08-10 18:27:55 HV000001: Hibernate Validator 8.0.0.Final
[INFO      ] 2023-08-10 18:27:55 Starting StreamApplication using Java 17.0.6 with PID 14944 (E:\workspace\Lilopop\stream\target\classes started by Administrator in E:\workspace\Lilopop)
[INFO      ] 2023-08-10 18:27:55 No active profile set, falling back to 1 default profile: "default"
[INFO      ] 2023-08-10 18:27:56 No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
[INFO      ] 2023-08-10 18:27:56 No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
[INFO      ] 2023-08-10 18:27:56 Bean 'org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration$IntegrationJmxConfiguration' of type [org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration$IntegrationJmxConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO      ] 2023-08-10 18:27:56 Bean 'org.springframework.cloud.stream.binder.rabbit.config.ExtendedBindingHandlerMappingsProviderConfiguration' of type [org.springframework.cloud.stream.binder.rabbit.config.ExtendedBindingHandlerMappingsProviderConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO      ] 2023-08-10 18:27:56 Bean 'rabbitExtendedPropertiesDefaultMappingsProvider' of type [org.springframework.cloud.stream.binder.rabbit.config.ExtendedBindingHandlerMappingsProviderConfiguration$$Lambda$583/0x0000000800f9b018] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO      ] 2023-08-10 18:27:56 Bean 'BindingHandlerAdvise' of type [org.springframework.cloud.stream.config.BindingHandlerAdvise] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO      ] 2023-08-10 18:27:56 Bean 'spelConverter' of type [org.springframework.cloud.stream.config.SpelExpressionConverterConfiguration$SpelConverter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO      ] 2023-08-10 18:27:56 Bean 'spring.jmx-org.springframework.boot.autoconfigure.jmx.JmxProperties' of type [org.springframework.boot.autoconfigure.jmx.JmxProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO      ] 2023-08-10 18:27:56 Bean 'org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration' of type [org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO      ] 2023-08-10 18:27:56 Bean 'mbeanServer' of type [com.sun.jmx.mbeanserver.JmxMBeanServer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO      ] 2023-08-10 18:27:56 Channel 'stream.logConsumer-in-0' has 1 subscriber(s).
[WARN      ] 2023-08-10 18:27:56 Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: org.springframework.amqp.rabbit.core.RabbitAdmin
[INFO      ] 2023-08-10 18:27:56 Registering MessageChannel errorChannel
[INFO      ] 2023-08-10 18:27:56 Registering MessageChannel logConsumer-in-0
[INFO      ] 2023-08-10 18:27:57 Registering MessageChannel nullChannel
[INFO      ] 2023-08-10 18:27:57 Registering MessageHandler _org.springframework.integration.errorLogger
[INFO      ] 2023-08-10 18:27:57 Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
[INFO      ] 2023-08-10 18:27:57 Channel 'stream.errorChannel' has 1 subscriber(s).
[INFO      ] 2023-08-10 18:27:57 started bean '_org.springframework.integration.errorLogger'
[INFO      ] 2023-08-10 18:27:57 Netty started on port 9800
[INFO      ] 2023-08-10 18:27:57 Creating binder: rabbit
[INFO      ] 2023-08-10 18:27:57 Constructing binder child context for rabbit
[INFO      ] 2023-08-10 18:27:57 Caching the binder: rabbit
[INFO      ] 2023-08-10 18:27:57 declaring queue for inbound: log.logconsumer, bound to: log
[INFO      ] 2023-08-10 18:27:57 Attempting to connect to: [127.0.0.1:5672]
[INFO      ] 2023-08-10 18:27:57 Created new connection: rabbitConnectionFactory#6cae2e4d:0/SimpleConnection@759a678a [delegate=amqp://guest@127.0.0.1:5672/, localPort=63060]
[INFO      ] 2023-08-10 18:27:57 Channel 'rabbit-1375633173.logConsumer-in-0.errors' has 1 subscriber(s).
[INFO      ] 2023-08-10 18:27:57 Channel 'rabbit-1375633173.logConsumer-in-0.errors' has 2 subscriber(s).
[INFO      ] 2023-08-10 18:27:57 started bean 'inbound.log.logconsumer'
[INFO      ] 2023-08-10 18:27:57 Started StreamApplication in 1.658 seconds (process running for 2.13)
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop1 password:123465 ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:UserVO{id=9, username='Lilopop1', email='null', phone='4567891', img='', token='eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJwaG9uZSI6IjQ1Njc4OTEiLCJpZCI6IjkiLCJleHAiOjE2ODk2ODAzMDIsImlhdCI6MTY4OTY3ODUwMiwidXNlciI6IkxpbG9wb3AxIn0.VefdK3UywCC0WeLPCeZsIOt_wFw2xiREQgZ0Tzt6zrk'}，执行结果为:成功
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop1 password:123465 ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:UserVO{id=9, username='Lilopop1', email='null', phone='4567891', img='', token='eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJwaG9uZSI6IjQ1Njc4OTEiLCJpZCI6IjkiLCJleHAiOjE2ODk2ODAzMDIsImlhdCI6MTY4OTY3ODUwMiwidXNlciI6IkxpbG9wb3AxIn0.VefdK3UywCC0WeLPCeZsIOt_wFw2xiREQgZ0Tzt6zrk'}，执行结果为:成功
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop1 password:123465 ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:UserVO{id=9, username='Lilopop1', email='null', phone='4567891', img='', token='eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJwaG9uZSI6IjQ1Njc4OTEiLCJpZCI6IjkiLCJleHAiOjE2ODk2ODAzMDIsImlhdCI6MTY4OTY3ODUwMiwidXNlciI6IkxpbG9wb3AxIn0.VefdK3UywCC0WeLPCeZsIOt_wFw2xiREQgZ0Tzt6zrk'}，执行结果为:成功
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop1 password:123465 ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:UserVO{id=9, username='Lilopop1', email='null', phone='4567891', img='', token='eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJwaG9uZSI6IjQ1Njc4OTEiLCJpZCI6IjkiLCJleHAiOjE2ODk3Njg1NDgsImlhdCI6MTY4OTc2Njc2OSwidXNlciI6IkxpbG9wb3AxIn0.fqiESyPM_AtRVTr3NE7ZAW5GTQfpIqjOZYWDf1PBv00'}，执行结果为:成功
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:null password:null ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:null password:null ,异常为：com.common.core.exception.GlobalException: 登陆失败，请检查账号密码，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:null password:null ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:null password:null ,异常为：com.common.core.exception.GlobalException: 登陆失败，请检查账号密码，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:null password:null ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:null password:null ,异常为：com.common.core.exception.GlobalException: 登陆失败，请检查账号密码，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:null password:null ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:null password:null ,异常为：com.common.core.exception.GlobalException: 登陆失败，请检查账号密码，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ,异常为：com.common.core.exception.GlobalException: 登陆失败，请检查账号密码，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ,异常为：com.common.core.exception.GlobalException: 登陆失败，请检查账号密码，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ,异常为：com.common.core.exception.GlobalException: 登陆失败，请检查账号密码，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ,异常为：com.common.core.exception.GlobalException: 登陆失败，请检查账号密码，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ,异常为：com.common.core.exception.GlobalException: 登陆失败，请检查账号密码，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ,异常为：com.common.core.exception.GlobalException: 登陆失败，请检查账号密码，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop08 password:123465 ,异常为：com.common.core.exception.GlobalException: 登陆失败，请检查账号密码，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop23 password:123465 ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:UserVO{id=31, username='Lilopop23', email='null', phone='45678923', img='', token='eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJwaG9uZSI6IjQ1Njc4OTIzIiwiaWQiOiIzMSIsImV4cCI6MTY4OTc3MDQwMSwiaWF0IjoxNjg5NzY4NjAzLCJ1c2VyIjoiTGlsb3BvcDIzIn0.cUxg7W3C128j0CtjlY1rilEkQhTzFHF-peaXTR1xzO0'}，执行结果为:成功
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop23 password:123465 ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:UserVO{id=31, username='Lilopop23', email='null', phone='45678923', img='', token='eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJwaG9uZSI6IjQ1Njc4OTIzIiwiaWQiOiIzMSIsImV4cCI6MTY4OTc3MDQwMSwiaWF0IjoxNjg5NzY4NjAzLCJ1c2VyIjoiTGlsb3BvcDIzIn0.cUxg7W3C128j0CtjlY1rilEkQhTzFHF-peaXTR1xzO0'}，执行结果为:成功
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop23 password:123465 ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:UserVO{id=31, username='Lilopop23', email='null', phone='45678923', img='', token='eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJwaG9uZSI6IjQ1Njc4OTIzIiwiaWQiOiIzMSIsImV4cCI6MTY4OTc3MDQwMSwiaWF0IjoxNjg5NzY4NjAzLCJ1c2VyIjoiTGlsb3BvcDIzIn0.cUxg7W3C128j0CtjlY1rilEkQhTzFHF-peaXTR1xzO0'}，执行结果为:成功
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop23 password:123465 ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:UserVO{id=31, username='Lilopop23', email='null', phone='45678923', img='', token='eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJwaG9uZSI6IjQ1Njc4OTIzIiwiaWQiOiIzMSIsImV4cCI6MTY4OTc3MDQwMSwiaWF0IjoxNjg5NzY4NjAzLCJ1c2VyIjoiTGlsb3BvcDIzIn0.cUxg7W3C128j0CtjlY1rilEkQhTzFHF-peaXTR1xzO0'}，执行结果为:成功
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop23 password:123465 ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:UserVO{id=31, username='Lilopop23', email='null', phone='45678923', img='', token='eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJwaG9uZSI6IjQ1Njc4OTIzIiwiaWQiOiIzMSIsImV4cCI6MTY4OTc3MDQwMSwiaWF0IjoxNjg5NzY4NjAzLCJ1c2VyIjoiTGlsb3BvcDIzIn0.cUxg7W3C128j0CtjlY1rilEkQhTzFHF-peaXTR1xzO0'}，执行结果为:成功
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop23 password:123465 ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:UserVO{id=31, username='Lilopop23', email='null', phone='45678923', img='', token='eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJwaG9uZSI6IjQ1Njc4OTIzIiwiaWQiOiIzMSIsImV4cCI6MTY4OTc3MDQwMSwiaWF0IjoxNjg5NzY4NjAzLCJ1c2VyIjoiTGlsb3BvcDIzIn0.cUxg7W3C128j0CtjlY1rilEkQhTzFHF-peaXTR1xzO0'}，执行结果为:成功
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:username:Lilopop23 password:123465 ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.LoginService.loginByUsername参数:UserVO{id=31, username='Lilopop23', email='null', phone='45678923', img='', token='eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJwaG9uZSI6IjQ1Njc4OTIzIiwiaWQiOiIzMSIsImV4cCI6MTY4OTc3MDQwMSwiaWF0IjoxNjg5NzY4NjAzLCJ1c2VyIjoiTGlsb3BvcDIzIn0.cUxg7W3C128j0CtjlY1rilEkQhTzFHF-peaXTR1xzO0'}，执行结果为:成功
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abc@qq.com', img='null'} ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:无返回值，执行结果为:成功
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abc@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=111, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abc@qq.com', img='null'} ,异常为：org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [user.user_unique_email]，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abc@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=112, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abc@qq.com', img='null'} ,异常为：org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [user.user_unique_email]，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abc@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=113, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abc@qq.com', img='null'} ,异常为：org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [user.user_unique_email]，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abc@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=114, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abc@qq.com', img='null'} ,异常为：org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [user.user_unique_email]，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abc@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=115, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abc@qq.com', img='null'} ,异常为：org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [user.user_unique_email]，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abc@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=116, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abc@qq.com', img='null'} ,异常为：org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [user.user_unique_email]，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:无返回值，执行结果为:成功
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='3d9188577cc9bfe9291ac66b5cc872b7', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=118, username='null', password='3d9188577cc9bfe9291ac66b5cc872b7', phone='null', email='abcd@qq.com', img='null'} ,异常为：org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [user.user_unique_email]，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='3d9188577cc9bfe9291ac66b5cc872b7', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='3d9188577cc9bfe9291ac66b5cc872b7', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='3d9188577cc9bfe9291ac66b5cc872b7', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='3d9188577cc9bfe9291ac66b5cc872b7', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='6c44e5cd17f0019c64b042e4a745412a', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ,异常为：com.common.core.exception.GlobalException: 用户已存在，执行结果为:失败
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='null', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='abcd@qq.com', img='null'} ，执行结果为:调用
[INFO      ] 2023-08-10 18:27:58 auth服务class com.auth.service.UserService.saveUser参数:false，执行结果为:成功
[INFO      ] 2023-08-10 18:28:34 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='Lilopop_001', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='null', img='null'} ，执行结果为:调用
[INFO      ] 2023-08-10 18:28:34 auth服务class com.auth.service.UserService.saveUser参数:true，执行结果为:成功
[INFO      ] 2023-08-10 18:28:57 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='Lilopop_002', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='null', img='null'} ，执行结果为:调用
[INFO      ] 2023-08-10 18:28:57 auth服务class com.auth.service.UserService.saveUser参数:true，执行结果为:成功
[INFO      ] 2023-08-10 18:31:42 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='Lilopop_002', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='null', img='null'} ，执行结果为:调用
[INFO      ] 2023-08-10 18:31:42 auth服务class com.auth.service.UserService.saveUser参数:true，执行结果为:成功
[INFO      ] 2023-08-10 18:33:25 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='Lilopop_002', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='null', img='null'} ，执行结果为:调用
[INFO      ] 2023-08-10 18:33:25 auth服务class com.auth.service.UserService.saveUser参数:true，执行结果为:成功
[INFO      ] 2023-08-10 18:53:14 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='Lilopop_002', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='null', img='null'} ，执行结果为:调用
[INFO      ] 2023-08-10 18:53:14 auth服务class com.auth.service.UserService.saveUser参数:false，执行结果为:成功
[INFO      ] 2023-08-10 18:57:14 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='Lilopop_003', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='123456@qq.cpm', img='null'} ，执行结果为:调用
[INFO      ] 2023-08-10 18:57:14 auth服务class com.auth.service.UserService.saveUser参数:true，执行结果为:成功
[INFO      ] 2023-08-10 18:57:54 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='Lilopop_003', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='null', img='null'} ，执行结果为:调用
[ERROR     ] 2023-08-10 18:57:54 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=124, username='Lilopop_003', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='null', img='null'} ,异常为：org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [user.user_unique_username]，执行结果为:失败
[INFO      ] 2023-08-10 19:18:04 auth服务class com.auth.service.UserService.saveUser参数:user:User{id=null, username='Lilopop_004', password='e10adc3949ba59abbe56e057f20f883e', phone='null', email='null', img='null'} ，执行结果为:调用
[INFO      ] 2023-08-10 19:18:04 auth服务class com.auth.service.UserService.saveUser参数:true，执行结果为:成功
[INFO      ] 2023-08-10 19:35:32 Waiting for workers to finish.
[INFO      ] 2023-08-10 19:35:33 Successfully waited for workers to finish.
[INFO      ] 2023-08-10 19:35:33 stopped bean 'inbound.log.logconsumer'
[INFO      ] 2023-08-10 19:35:33 Registering MessageChannel rabbit-1375633173.logConsumer-in-0.errors
[INFO      ] 2023-08-10 19:35:33 Channel 'stream.rabbit-1375633173.logConsumer-in-0.errors' has 1 subscriber(s).
[INFO      ] 2023-08-10 19:35:33 Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
[INFO      ] 2023-08-10 19:35:33 Channel 'stream.errorChannel' has 0 subscriber(s).
[INFO      ] 2023-08-10 19:35:33 stopped bean '_org.springframework.integration.errorLogger'
